api_server: "http://127.0.0.1:5001"
api_type: "koboldcpp"
history_path: "./histories"
checkpoint_path: "./checkpoints"
checkpoint_keep: 20
default_model: "sample-model"
tool_format: "typescript"  # json | typescript | python
# Pattern match?
available_models:
  - "models/sample-model.yaml"
